### ISSUE TITLE
SPIFFS

### ISSUE THREAD

**Issue by rel1ct** [copercini/arduino-esp32-SPIFFS#1]
`0	Object
type	"file"
name	"//spiffs"
1	Object
type	"file"
name	"/ace.js.gz"
2	Object
type	"file"
name	"/favicon.ico"
3	Object
type	"dir"
name	"/img"
4	Object
type	"file"
name	"/edit.htm"
5	Object
type	"file"
name	"/index.htm"`
File "//spiffs" ???. In file names "/" ???.

**Comment by copercini** [comment]
Fixed!
Thanks for report!
