### ISSUE TITLE
Stream file via webserver failes

### ISSUE THREAD

**Issue by everslick** [copercini/arduino-esp32-SPIFFS#6]
Has anybody combined webserver_tng and SPIFFS yet? spiffs works, but i cannot stream a file via http like this.

```
File file = SPIFFS.open("/foo.txt", FILE_READ);
webserver.streamFile(file, "text/plain");
file.close();
```

the server closes the connection without sending a single byte to the browser.

**Comment by copercini** [comment]
Solved updating WebServer_tng files. More details here: https://github.com/espressif/arduino-esp32/issues/312#issuecomment-317907145
